:bug: fix: authDomain is required for mobile
The error was:
```
FirebaseError: Firebase: Error (auth/auth-domain-config-required).
```
Note that I haven't set that up for Rointe Connect ad I don't have an
account to test yet.